# Generated by Django 6.0.8 on 2026-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='problem_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='problem_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='vehicle_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='vehicle_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
