# Generated by Django 6.0.8 on 2026-09-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_assistancerequest_problem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='location_access',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='location_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='location_direction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='location_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='location_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
