# Generated by Django 6.0.8 on 2026-09-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_assistancerequest_location_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='assistance_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='assistance_needs',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='occupant_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='occupant_safety',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
