# Generated by Django 6.0.8 on 2026-09-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_assistancerequest_assistance_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='contact_first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='contact_last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='contact_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='contact_phone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
